import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
function App(){const[open,setOpen]=useState(false);const[status,setStatus]=useState('');return <>
  <a className="skip" href="#main">Skip to content</a>
  <header className="top"><a className="wordmark" href="#">AD<span> / Art Director</span></a><button aria-expanded={open} aria-controls="menu" onClick={()=>setOpen(!open)} onKeyDown={e=>{if(e.key==='Escape')setOpen(false)}}>Menu</button><nav id="menu" hidden={!open} aria-label="Main"><a href="#process">The process</a><a href="#try">Try locally</a></nav></header>
  <main id="main"><section className="hero"><div><p className="eyebrow">DESIGN DECISIONS, MADE EXPLICIT</p><h1>A direction.<br/>Then a reason.</h1><p className="intro">Give your coding agent a visual contract it can build against—and evidence it can come back to.</p><a className="cta" href="#process">Explore the workflow <span aria-hidden="true">↗</span></a><p className="note">Local developer preview · No extra model API key</p></div><figure className="stage"><div className="stage-label">01 / DIRECTION STUDY</div><div className="specimen"><span>Form follows</span><strong>intent.</strong><div className="ruler"/><p>Composition → Contract → Evidence</p></div><figcaption>Typographic study. No customer claims or product metrics.</figcaption></figure></section>
  <section id="process" className="process"><h2>Keep the decisions.<br/>Check the result.</h2><ol><li><span>01</span><h3>Choose a composition</h3><p>Compare genuinely different structures using your own content.</p></li><li><span>02</span><h3>Make it a contract</h3><p>Record typography, layout, states and the things that must stay true.</p></li><li><span>03</span><h3>Return with evidence</h3><p>Inspect the rendered interface. Separate measurable failures from visual judgment.</p></li></ol></section>
  <section id="try" className="try"><div><p className="eyebrow">START WITH A REAL TASK</p><h2>What should this<br/>interface help people do?</h2></div><form onSubmit={e=>{e.preventDefault();setStatus('Saved for this demo session. Nothing was sent.')}}><label htmlFor="task">Primary task</label><input id="task" name="task" required placeholder="Find and read a project case study"/><button className="cta">Save demo task</button><p role="status">{status}</p></form></section></main><footer>Art Director MCP · Development demo · Original text and CSS artwork</footer></>}
createRoot(document.getElementById('root')).render(<App/>);
